#!/usr/bin/env node
/**
 * Rebuilds dist/ -- the folder that gets deployed.
 *
 * The app is published from dist/ rather than from the project root because the
 * root also holds the tests, the context documents, and whatever screenshots
 * are lying around at the time. A static host publishes every byte it is given
 * and keeps serving it, so the deploy folder is curated deliberately rather
 * than being "the project".
 *
 * dist/ is wiped before it is rebuilt. Copying over the top leaves files from
 * the previous build sitting in it, and a stale .js that index.html no longer
 * references is invisible in a browser -- it simply never loads -- while still
 * being public on the CDN.
 *
 * The last step re-reads the *copied* index.html and checks that every asset it
 * references actually made it across. A missing file here becomes a 404 in
 * production, and for a <script> that means a blank page and no error a user
 * could report. Cheap to catch now, expensive to diagnose from a phone.
 */
import { rm, mkdir, cp, readFile, writeFile, access, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = join(ROOT, "dist");

// Everything the app needs in order to run, and nothing else.
const ENTRIES = ["index.html", "css", "js"];

await rm(DIST, { recursive: true, force: true });
await mkdir(DIST, { recursive: true });

for (const entry of ENTRIES) {
  await cp(join(ROOT, entry), join(DIST, entry), { recursive: true });
}

// Headers for a drag-and-drop deploy, which publishes exactly the folder it is
// handed and runs no build step. They therefore have to travel *inside* dist/.
//
// There is deliberately no [build] section here. This file sits at the root of
// what gets published, and a publish path pointing at "dist" from within dist/
// describes a folder that does not exist -- which is precisely how a drag of the
// project root failed: Netlify found the root netlify.toml, honoured its
// publish rule, and went looking for a dist/ the drag had never included.
//
// If a host ignores this file, the only loss is two response headers. It cannot
// break the deploy, which is why it is safe to ship without knowing the answer.
await writeFile(join(DIST, "netlify.toml"), `# Generated by tools/build.mjs -- do not edit; edit the root netlify.toml.
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
`, "utf8");

// Every src/href in the copied HTML must resolve inside dist/.
const html = await readFile(join(DIST, "index.html"), "utf8");
const refs = [...html.matchAll(/(?:src|href)="([^"]+)"/g)]
  .map((match) => match[1])
  .filter((ref) => !/^(?:https?:|data:|#|mailto:|\/\/)/.test(ref));

const missing = [];
for (const ref of refs) {
  try {
    await access(join(DIST, ref));
  } catch {
    missing.push(ref);
  }
}

if (missing.length) {
  console.error(`build failed -- index.html references ${missing.length} file(s) not in dist/:`);
  for (const ref of missing) console.error(`  ${ref}`);
  process.exit(1);
}

let files = 0;
for (const entry of ENTRIES) {
  if (entry === "index.html") { files += 1; continue; }
  const walk = async (dir) => {
    for (const item of await readdir(dir, { withFileTypes: true })) {
      if (item.isDirectory()) await walk(join(dir, item.name));
      else files += 1;
    }
  };
  await walk(join(DIST, entry));
}

files += 1; // the generated netlify.toml, which is written rather than copied

console.log(`dist/ rebuilt: ${files} files, ${refs.length} referenced assets all present`);
